---
- hosts: 172.22.2.145
  become: yes
  tasks:
    - name: Update apt cache and make sure the follwing packages is installed for Active Directory Integration
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - realmd
        - libnss-sss
        - libpam-sss
        - sssd
        - sssd-tools
        - adcli
        - samba-common-bin
        - oddjob
        - oddjob-mkhomedir
        - packagekit
