---
- hosts: 172.22.2.145
  become: yes
  tasks:
    - name: Update apt cache and make sure the follwing packages is installed for Active Directory Integration
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - sssd
        - realmd
        - oddjob-mkhomedir
        - adcli
        - samba-common
        - samba-common-tools
        - krb5-workstation
        - openldap-clients
        - policycoreutils-python
