---
- hosts: 172.22.2.195
  become: true

  tasks:
    - name: Install dependencies
      apt:
        name:
          - realmd
          - sssd
          - sssd-tools
          - adcli
          - krb5-user
          - packagekit
        state: present

    - name: Join Ubuntu to Active Directory
      shell: |
        realm discover your_domain_name
        realm join --verbose your_domain_name -U your_domain_admin_account

    - name: Configure SSSD
      copy:
        src: /path/to/sssd.conf
        dest: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: 0600
      notify:
        - restart sssd.service

  handlers:
    - name: restart sssd.service
      service:
        name: sssd.service
        state: restarted
